/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopracticointegrador.Vista;
import trabajopracticointegrador.Logica.ControlAccesoInterfaz;
import trabajopracticointegrador.Logica.ControlAcceso;
import trabajopracticointegrador.Socio;
import trabajopracticointegrador.ConexionDB.SocioDAO;
import trabajopracticointegrador.ConexionDB.SuscripcionDAO;
import trabajopracticointegrador.ConexionDB.Conexion;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridLayout;
import java.awt.BorderLayout;


/**
 *
 * @author fermi
 */
public class ControlAccesoFrame extends javax.swing.JFrame {
    
    private ControlAcceso control;
    private ControlAccesoListener listener;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ControlAccesoFrame.class.getName());

    /**
     * Creates new form ControlAccesoFrame
     */
    public ControlAccesoFrame(Conexion conn) {
        this.listener = new ControlAccesoListener();
        this.control = new ControlAcceso(listener, conn);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarSimulacion = new javax.swing.JButton();
        txtIngresoDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciarSimulacion.setText("Iniciar simulacion");
        btnIniciarSimulacion.addActionListener(this::btnIniciarSimulacionActionPerformed);

        txtIngresoDni.addActionListener(this::txtIngresoDniActionPerformed);

        jLabel1.setText("Ingrese DNI:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIniciarSimulacion)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(txtIngresoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngresoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(120, 120, 120)
                .addComponent(btnIniciarSimulacion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSimulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSimulacionActionPerformed

    private void txtIngresoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresoDniActionPerformed
        
        String dni = txtIngresoDni.getText().trim();
        control.procesarIngreso(dni);
    }//GEN-LAST:event_txtIngresoDniActionPerformed

        private class ControlAccesoListener implements ControlAccesoInterfaz {

            // CONSTRUCTOR
            public ControlAccesoListener() {

            }

            @Override
            public void accesoConcedido(Socio socio) {
                dialogAccesoConcedido(socio);
            }

            @Override 
            public void accesoParcial(Socio socio) {
                dialogAccesoParcial(socio);
            }

            public void accesoDenegado(String mensajeError) {
                dialogAccesoDenegado(mensajeError);
            }
        }
    
    public void dialogAccesoConcedido(Socio socio) {
        
        // DATOS DEL SOCIO 
        JDialog dialog = new JDialog(this, "Datos de socio", true);
        dialog.setSize(350, 400);
        dialog.setLayout(new BorderLayout());
        
        // PANEL PRINCIPAL CON PADDING
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        mostrarDatosSocio(socio, panel);

        // agregar boton de cierre
    }
    
    public void dialogAccesoDenegado(String mensajeError) {
        JDialog dialog = new JDialog(this, "", true);
        dialog.setSize(350, 400);
        dialog.setLayout(new BorderLayout());
        
        // PANEL PRINCIPAL CON PADDING
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        // MENSAJE DE ERROR
        panel.add(new JLabel(mensajeError));

        // agregar boton de cierre
    }
    
    public void dialogAccesoParcial(Socio socio) {
       
        // CREACION DE NUEVA VENTANA DIALOG
        JDialog dialog = new JDialog(this, "Datos de socio", true);
        dialog.setSize(350, 400);
        dialog.setLayout(new BorderLayout());

        // PANEL PRINCIPAL CON PADDING
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        mostrarDatosSocio(socio, panel);
        
        // MENSAJE DE AVISO
        panel.add(new JLabel("Debe abonar la suscripcion"));

        // agregar boton de cierre
    }
    
    public void mostrarDatosSocio(Socio socio, JPanel panel) {
        
        // DATOS DE PERSONA
        panel.add(new JLabel("Nombre:"));
        panel.add(new JLabel(socio.getNombre()));

        panel.add(new JLabel("Apellido:"));
        panel.add(new JLabel(socio.getApellido()));

        panel.add(new JLabel("DNI:"));
        panel.add(new JLabel(String.valueOf(socio.getDNI())));

        if (socio.isActivo()) {
            panel.add(new JLabel("Socio activo"));
        } else {
            panel.add(new JLabel("Socio inactivo"));
        }

        // DATOS DE SUSCRIPCION
        panel.add(new JLabel("Plan:"));
        panel.add(new JLabel(socio.getSuscripcion().getDescripcion()));

        panel.add(new JLabel("Vencimiento:"));
        panel.add(new JLabel(socio.getSuscripcion().getFechaFin().toString()));
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSimulacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIngresoDni;
    // End of variables declaration//GEN-END:variables
}
