/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopracticointegrador.Vista;
import trabajopracticointegrador.Logica.ControlAccesoInterfaz;
import trabajopracticointegrador.Socio;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridLayout;
import java.awt.BorderLayout;


/**
 *
 * @author fermi
 */
public class ControlAccesoFrame extends javax.swing.JFrame implements ControlAccesoInterfaz {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ControlAccesoFrame.class.getName());

    /**
     * Creates new form ControlAccesoFrame
     */
    public ControlAccesoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarSimulacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciarSimulacion.setText("Iniciar simulacion");
        btnIniciarSimulacion.addActionListener(this::btnIniciarSimulacionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnIniciarSimulacion)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnIniciarSimulacion)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSimulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSimulacionActionPerformed

    // METODOS DE DE LA INTERFAZ
    @Override
    public void accesoConcedido(Socio socio) {
        
        // DATOS DEL SOCIO 
        JDialog dialog = new JDialog(this, "Datos de socio", true);
        dialog.setSize(350, 400);
        dialog.setLayout(new BorderLayout());
        
        // PANEL PRINCIPAL CON PADDING
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        mostrarDatosSocio(socio, panel);

        // agregar boton de cierre
    }
    
    @Override
    public void accesoDenegado(String mensajeError) {
        JDialog dialog = new JDialog(this, "", true);
        dialog.setSize(350, 400);
        dialog.setLayout(new BorderLayout());
        
        // PANEL PRINCIPAL CON PADDING
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        // MENSAJE DE ERROR
        panel.add(new JLabel(mensajeError));

        // agregar boton de cierre
    }
    
    @Override
    public void accesoParcial(Socio socio) {
       
        // CREACION DE NUEVA VENTANA DIALOG
        JDialog dialog = new JDialog(this, "Datos de socio", true);
        dialog.setSize(350, 400);
        dialog.setLayout(new BorderLayout());

        // PANEL PRINCIPAL CON PADDING
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        mostrarDatosSocio(socio, panel);
        
        // MENSAJE DE AVISO
        panel.add(new JLabel("Debe abonar la suscripcion"));

        // agregar boton de cierre
    }
    
    public void mostrarDatosSocio(Socio socio, JPanel panel) {
        
        // DATOS DE PERSONA
        panel.add(new JLabel("Nombre:"));
        panel.add(new JLabel(socio.getNombre()));

        panel.add(new JLabel("Apellido:"));
        panel.add(new JLabel(socio.getApellido()));

        panel.add(new JLabel("DNI:"));
        panel.add(new JLabel(String.valueOf(socio.getDNI())));

        if (socio.isActivo()) {
            panel.add(new JLabel("Socio activo"));
        } else {
            panel.add(new JLabel("Socio inactivo"));
        }

        // DATOS DE SUSCRIPCION
        panel.add(new JLabel("Plan:"));
        panel.add(new JLabel(socio.getSuscripcion().getDescripcion()));

        panel.add(new JLabel("Vencimiento:"));
        panel.add(new JLabel(socio.getSuscripcion().getFechaFin().toString()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ControlAccesoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSimulacion;
    // End of variables declaration//GEN-END:variables
}
