/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopracticointegrador.Vista;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import trabajopracticointegrador.ConexionDB.Conexion;
import trabajopracticointegrador.ConexionDB.IngresoDAO;
import trabajopracticointegrador.ConexionDB.SocioDAO;
import trabajopracticointegrador.ConexionDB.SuscripcionDAO;
import trabajopracticointegrador.Ingreso;
import trabajopracticointegrador.Socio;

/**
 *
 * @author fermi
 */
public class ListaIngresosFrame extends javax.swing.JFrame {
    
    private Conexion conexion;
    private SocioDAO socio_dao;
    private SuscripcionDAO suscripcion_dao;
    private IngresoDAO ingreso_dao;
    
    private DefaultTableModel modelo;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListaIngresosFrame.class.getName());

    /**
     * Creates new form ListaIngresosFrame
     */
    public ListaIngresosFrame(Conexion conexion) {
        initComponents();
        
        this.conexion = conexion;
        
        suscripcion_dao = new SuscripcionDAO(conexion);
        socio_dao = new SocioDAO(conexion, suscripcion_dao);
        ingreso_dao = new IngresoDAO(conexion);
        
        modelo = new DefaultTableModel(new Object[]{"ID", "Nombre", "Apellido", "Fecha", "Hora", "Pagó"}, 0);
        tblSocios.setModel(modelo);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        lblListaIngresos = new javax.swing.JLabel();
        lblBuscarDni = new javax.swing.JLabel();
        txtBuscarDni = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        tblIngresos = new javax.swing.JScrollPane();
        tblSocios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        lblListaIngresos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblListaIngresos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaIngresos.setText("LISTA DE INGRESOS");

        lblBuscarDni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscarDni.setText("Buscar DNI:");

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "DNI", "Telefono", "Fecha Alta"
            }
        ));
        tblSocios.setToolTipText("");
        tblIngresos.setViewportView(tblSocios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(lblListaIngresos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnBuscar)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscarDni)
                            .addComponent(tblIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(btnVolver)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblListaIngresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        suscripcion_dao = new SuscripcionDAO(conexion);
        socio_dao = new SocioDAO(conexion, suscripcion_dao);

        Socio socio;
        
        String dni = txtBuscarDni.getText().trim();
        
        modelo.setRowCount(0);

        if (dni.isEmpty()) {
            ArrayList<Ingreso> ingresos = ingreso_dao.obtenerIngresos();
            
            modelo.setRowCount(0);

            for (Ingreso ingreso : ingresos) {
                socio = socio_dao.obtenerSocioPorId(ingreso.getId_socio());
                
                modelo.addRow(new Object[]{
                    ingreso.getId_ingreso(),
                    socio.getNombre(),
                    socio.getApellido(),
                    ingreso.getFecha_hora().toLocalDate(),
                    ingreso.getFecha_hora().toLocalTime(),
                    ingreso.getAcceso()
                });
            }

            if (ingresos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay ingresos registrados");
            }
        } else {

            socio = socio_dao.obtenerSocio(dni);
            
            if (socio != null) {
                ArrayList<Ingreso> ingresos = ingreso_dao.obtenerIngresosSocio(socio.getId_Socio());

                if (!ingresos.isEmpty()) {

                    for (Ingreso ingreso : ingresos) {
                        modelo.addRow(new Object[]{
                            ingreso.getId_ingreso(),
                            socio.getNombre(),
                            socio.getApellido(),
                            ingreso.getFecha_hora().toLocalDate(),
                            ingreso.getFecha_hora().toLocalTime(),
                            ingreso.getAcceso()
                        });
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ingresos no registrados");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Socio no encontrado");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblBuscarDni;
    private javax.swing.JLabel lblListaIngresos;
    private javax.swing.JScrollPane tblIngresos;
    private javax.swing.JTable tblSocios;
    private javax.swing.JTextField txtBuscarDni;
    // End of variables declaration//GEN-END:variables
}
