/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopracticointegrador.Vista;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import trabajopracticointegrador.ConexionDB.Conexion;
import trabajopracticointegrador.ConexionDB.EmpleadoDAO;
import trabajopracticointegrador.ConexionDB.RolDAO;
import trabajopracticointegrador.ConexionDB.SocioDAO;
import trabajopracticointegrador.ConexionDB.SuscripcionDAO;
import trabajopracticointegrador.Empleado;
import trabajopracticointegrador.Entrenador;
import trabajopracticointegrador.Socio;
import trabajopracticointegrador.Suscripcion;

/**
 *
 * @author fermi
 */
public class ListaEmpleadoFrame extends javax.swing.JFrame {
    
    private EmpleadoDAO empleado_dao;
    private RolDAO rol_dao;
    private Conexion conn;
    
    private ArrayList<String> roles;
    
    private Empleado empleado;
    private Entrenador entrenador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListaEmpleadoFrame.class.getName());

    /**
     * Creates new form ListaEmpleadoFrame
     */
    public ListaEmpleadoFrame(Conexion conn) {
        initComponents();
        
        this.conn = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAgregar)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        JDialog dialog = new JDialog(this, "Datos de empleado", true);
        dialog.setSize(500, 550);
        dialog.setLayout(new BorderLayout());
        
        // PANEL PRINCIPAL CON PADDING
        JPanel panel = new JPanel(new GridLayout(8, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        // CAMPOS PARA INGRESO DE DATOS
        JTextField txtNombre = new JTextField();
        JTextField txtApellido = new JTextField();
        JTextField txtFechaNacimiento = new JTextField();
        JTextField txtDni = new JTextField();
        JTextField txtDireccion = new JTextField();
        JTextField txtTelefono = new JTextField();
        
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        empleado_dao = new EmpleadoDAO(conn);
        rol_dao = new RolDAO(conn);
        
        roles = rol_dao.obtenerRoles();
        
        JComboBox cmbRol = new JComboBox();
        
        for (String rol : roles) {
            cmbRol.addItem(rol);
        }
        
        panel.add(new JLabel("Nombre"));
        panel.add(txtNombre);
        
        panel.add(new JLabel("Apellido"));
        panel.add(txtApellido);
        
        panel.add(new JLabel("DNI"));
        panel.add(txtDni);
        
        panel.add(new JLabel("Fecha de nacimiento (dd/MM/aaaa)"));
        panel.add(txtFechaNacimiento);
        
        panel.add(new JLabel("Direccion"));
        panel.add(txtDireccion);
        
        panel.add(new JLabel("Numero de telefono"));
        panel.add(txtTelefono);
        
        panel.add(new JLabel("Rol"));
        panel.add(cmbRol);
        
        // AGREGO EL PANEL AL DIALOG
        dialog.add(panel, BorderLayout.CENTER);
        
        // PANEL PARA BOTONES
        JPanel panelBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        
        // BOTON GUARDAR 
        JButton botonGuardar = new JButton("Guardar");
        botonGuardar.addActionListener(e -> {
            empleado = new Empleado();
            
            empleado.setNombre(txtNombre.getText().trim());
            empleado.setApellido(txtApellido.getText().trim());
            empleado.setDNI(txtDni.getText().trim());
            empleado.setFechaNacimiento(LocalDate.parse(txtFechaNacimiento.getText().trim(), formateador));
            empleado.setDireccion(txtDireccion.getText().trim());
            empleado.setNumeroTelefono(txtTelefono.getText().trim());
            
            String rol_seleccionado = cmbRol.getSelectedItem().toString();
            boolean plan_encontrado = false;
            
            for (Suscripcion plan : planes) {
                if (plan.getDescripcion().equals(plan_descripcion)) {
                    asignarDatosPlan(plan);
                    socio.setSuscripcion(suscripcion);
                    plan_encontrado = true;
                    break;
                }
            }
            
            if (plan_encontrado == true) {
                try {
                    if (socio_dao.insertarSocio(socio) == true) {
                        JOptionPane.showMessageDialog(dialog, "Socio " + socio.getApellido() + " registrado correctamente.", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(dialog, "Error crítico al intentar guardar en la Base de Datos.", "Error de Persistencia", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    System.getLogger(ListaSocioFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                
                
            } else {
                JOptionPane.showMessageDialog(dialog, "Error interno: No se pudo mapear la suscripción.", "Error Técnico", JOptionPane.ERROR_MESSAGE);
            }
        });
        panelBotones.add(botonGuardar);
        
        // BOTON DE CIERRE
        JButton botonCierre = new JButton("Cerrar");
        botonCierre.addActionListener(e -> dialog.dispose());
        panelBotones.add(botonCierre);
        
        // AGREGO EL PANEL DE BOTONES AL DIALOG
        dialog.add(panelBotones, BorderLayout.SOUTH);
        
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    // End of variables declaration//GEN-END:variables
}
