/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopracticointegrador.Vista;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trabajopracticointegrador.ConexionDB.Conexion;
import trabajopracticointegrador.ConexionDB.SocioDAO;
import trabajopracticointegrador.ConexionDB.SuscripcionDAO;
import trabajopracticointegrador.Socio;
import trabajopracticointegrador.Suscripcion;
import trabajopracticointegrador.SuscripcionCupo;
import trabajopracticointegrador.SuscripcionLibre;
import java.sql.SQLException;

/**
 *
 * @author fermi
 */
public class PagarSuscripcionFrame extends javax.swing.JFrame {
    
    private Conexion conexion;
    private DefaultTableModel modelo;
    private SuscripcionDAO suscripcion_dao;
    private SocioDAO socio_dao;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagarSuscripcionFrame.class.getName());

    /**
     * Creates new form PagarSuscripcionFrame
     */
    public PagarSuscripcionFrame(Conexion conexion) {
        initComponents();
        
        this.conexion = conexion;
        
        suscripcion_dao = new SuscripcionDAO(conexion);
        socio_dao = new SocioDAO(conexion, suscripcion_dao);
        
        txtSocioId.setEditable(false);
        txtNombreSocio.setEditable(false);
        txtApellidoSocio.setEditable(false);
        
        txtSocioId.setBackground(this.getBackground());
        txtNombreSocio.setBackground(this.getBackground());
        txtApellidoSocio.setBackground(this.getBackground());
        
        modelo = new DefaultTableModel(new Object[]{"ID", "Descripcion", "Precio"},0);
        tblPlanes.setModel(modelo);
    }
    
    public PagarSuscripcionFrame(Conexion conexion, Socio socio) {
        initComponents();
        
        this.conexion = conexion;
        
        suscripcion_dao = new SuscripcionDAO(conexion);
        socio_dao = new SocioDAO(conexion, suscripcion_dao);
        
        txtSocioId.setEditable(false);
        txtNombreSocio.setEditable(false);
        txtApellidoSocio.setEditable(false);
        
        txtSocioId.setBackground(this.getBackground());
        txtNombreSocio.setBackground(this.getBackground());
        txtApellidoSocio.setBackground(this.getBackground());
        
        modelo = new DefaultTableModel(new Object[]{"ID", "Descripcion", "Precio", "Cantidad dias", "Cantidad cupos"},0);
        tblPlanes.setModel(modelo);
        
        txtSocioId.setText(String.valueOf(socio.getId_Socio()));
        txtNombreSocio.setText(socio.getNombre());
        txtApellidoSocio.setText(socio.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanes = new javax.swing.JTable();
        cmbTipoPlan = new javax.swing.JComboBox<>();
        txtSocioId = new javax.swing.JTextField();
        txtNombreSocio = new javax.swing.JTextField();
        txtApellidoSocio = new javax.swing.JTextField();
        btnAsignarPlan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblListaSocios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPlanes);

        cmbTipoPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbTipoPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Planes Libres", "Planes por Cupos" }));
        cmbTipoPlan.setPreferredSize(new java.awt.Dimension(155, 27));
        cmbTipoPlan.addActionListener(this::cmbTipoPlanActionPerformed);

        txtSocioId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSocioId.setText("ID");

        txtNombreSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombreSocio.setText("Nombre");

        txtApellidoSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtApellidoSocio.setText("Apellido");

        btnAsignarPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAsignarPlan.setText("Asignar plan");
        btnAsignarPlan.addActionListener(this::btnAsignarPlanActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        lblListaSocios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblListaSocios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaSocios.setText("LISTA DE PLANES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSocioId)
                                    .addComponent(txtNombreSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbTipoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAsignarPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtApellidoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lblListaSocios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblListaSocios)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSocioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoPlanActionPerformed
        // TODO add your handling code here:
        
        modelo.setRowCount(0);
        
        String opcionSeleccionada = cmbTipoPlan.getSelectedItem().toString();
        
        if (opcionSeleccionada.equals("Planes Libres")) {
            ArrayList<SuscripcionLibre> planes;
            
            planes = suscripcion_dao.obtenerPlanesLibres();
            
            modelo.setRowCount(0);
            
            for (SuscripcionLibre plan : planes) {
                modelo.addRow(new Object[]{
                    plan.getId_plan(),
                    plan.getDescripcion(),
                    plan.getValor(),
                    plan.getDiasTotal()
                });
            }
        } else if (opcionSeleccionada.equals("Planes por Cupos")) {
            ArrayList<SuscripcionCupo> planes;
            
            planes = suscripcion_dao.obtenerPlanesPorCupos();
            
            modelo.setRowCount(0);
            
            for (SuscripcionCupo plan : planes) {
                modelo.addRow(new Object[]{
                    plan.getId_plan(),
                    plan.getDescripcion(),
                    plan.getValor(),
                    plan.getDiasTotal(),
                    plan.getCuposRestantes()
                });
            }
        }
    }//GEN-LAST:event_cmbTipoPlanActionPerformed

    private void btnAsignarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPlanActionPerformed
        // TODO add your handling code here:
                
        int filaPlan = tblPlanes.getSelectedRow();
        String idSocioTexto = txtSocioId.getText().trim();

        if (filaPlan == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un plan de la tabla.");
            return;
        }
        if (idSocioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe buscar y localizar un socio válido primero.");
            return;
        }

        int id_plan = Integer.parseInt(modelo.getValueAt(filaPlan, 0).toString());
        int id_socio = Integer.parseInt(idSocioTexto);
        
        if (suscripcion_dao.tieneSuscripcionActiva(id_socio)) {
            JOptionPane.showMessageDialog(
                this,
                "El socio ya posee una suscripción activa."
            );
            return;
        }
        
        int cantidadDias = Integer.parseInt(modelo.getValueAt(filaPlan, 3).toString());
        Object valorCupos = null;

        if (modelo.getColumnCount() > 4) {
            valorCupos = modelo.getValueAt(filaPlan, 4);
        } 

        LocalDate fechaInicio = LocalDate.now();
        LocalDate fechaFin = fechaInicio.plusDays(cantidadDias);

        boolean exito = false;

        try {
            if (valorCupos != null && !valorCupos.toString().trim().isEmpty()) {

                int cuposIniciales = Integer.parseInt(valorCupos.toString().trim());

                SuscripcionCupo suscripcionCupo = new SuscripcionCupo();
                suscripcionCupo.setId_plan(id_plan);
                suscripcionCupo.setFechaInicio(fechaInicio);
                suscripcionCupo.setFechaFin(fechaFin);
                suscripcionCupo.setCuposRestantes(cuposIniciales);

                exito = suscripcion_dao.insertarSuscripcionCupo(suscripcionCupo, id_socio);

            } else {

                SuscripcionLibre suscripcionLibre = new SuscripcionLibre();
                suscripcionLibre.setId_plan(id_plan);
                suscripcionLibre.setFechaInicio(fechaInicio);
                suscripcionLibre.setFechaFin(fechaFin);

                exito = suscripcion_dao.insertarSuscripcionLibre(suscripcionLibre, id_socio);
            }

            if (exito) {
                JOptionPane.showMessageDialog(this, 
                        "Suscripción asignada correctamente.\nFecha de vencimiento: " + fechaFin, 
                        "Operación Exitosa", 
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar la suscripción en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en el formato de los datos numéricos del plan.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAsignarPlanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarPlan;
    private javax.swing.JComboBox<String> cmbTipoPlan;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListaSocios;
    private javax.swing.JTable tblPlanes;
    private javax.swing.JTextField txtApellidoSocio;
    private javax.swing.JTextField txtNombreSocio;
    private javax.swing.JTextField txtSocioId;
    // End of variables declaration//GEN-END:variables
}
